### ISSUE TITLE
Premium Plugin causing technical issue – [Galena Lodge] Your Site is Experiencing a Tech

### ISSUE THREAD

**Issue by sstudebaker** [kokomomtl/wc-product-customer-list#1]
Howdy!

Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.
...

https://www.galenalodge.com/wp-login.php?action=enter_recovery_mode&rm_token=TMsCS8urBsgRrXRkON3y0n&rm_key=7DHGVNKFCrBY2tjm4uheFX

To keep your site safe, this link will expire in 1 day. Don’t worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

Error Details
=============
An error of type E_ERROR was caused in line 12628 of the file /home/galenalodge/www/wp-content/plugins/wc-product-customer-list-premium/freemius/includes/class-freemius.php. Error message: Uncaught Error: Call to undefined function get_blog_list() in /home/galenalodge/www/wp-content/plugins/wc-product-customer-list-premium/freemius/includes/class-freemius.php:12628
Stack trace:
#0 /home/galenalodge/www/wp-content/plugins/wc-product-customer-list-premium/freemius/includes/class-freemius.php(12697): Freemius::get_sites()
#1 /home/galenalodge/www/wp-content/plugins/wc-product-customer-list-premium/freemius/includes/class-freemius.php(17035): Freemius->get_blog_install_map()
#2 /home/galenalodge/www/wp-content/plugins/wc-product-customer-list-premium/freemius/includes/class-fs-plugin-updater.php(122): Freemius->has_any_active_valid_license()
#3 /home/galenalodge/www/wp-content/plugins/wc-product-customer-list-premium/freemius/includes/class-fs-plugin-updater.php(72): FS_Plugin_Updater->filters()
#4 /home/galenalodge/www/wp-content/plugins/wc-product-customer-list-premium/freemius/includes/class-fs-plugin-updater.php(59): FS_Plugin_Updater->__construct(Object(Freemius))
#5 /home/galenalodge/www/wp-c

The page I need help with: https://www.galenalodge.com/

**Comment by kokomomtl** [comment]
Thank you for the report. We are aware of the issue and will be releasing a fix tomorrow.

Thierry

**Comment by kokomomtl** [comment]
I just pushed an update that should solve this issue, it can be downloaded in this repository or on wordpress. Let me know if it fixes it. Thank-you!
